#+TITLE: Rust Exercises
#+OPTIONS: toc:nil

* Rust Exercises
:PROPERTIES:
:UNNUMBERED: notoc
:END:

* Overview
This repository is home to the work I have done while learning the
Rust programming language. All of the exercises I have done so far
have come from a single book: /The Rust Programming Language/, also
known simply as the Rust book. I have completed several chapters worth
of exercises, and I am still working through the book. My goal is to
understand Rust's design decisions, what differentiates it from
languages like C, and how to write clean, efficient code.

* /The Rust Programming Language/
My exercises from this book are currently just in =book=. Within that
directory, there is a =chapters= directory, which is for working with
code given as part of the book's chapters. The other directory within
is =exercises=, which is where I have been completing all of the end
of chapter exercises.

* /Programming Rust/
I have not started on this book from O'Reilly, but it is the next one
I will read after the Rust book. I hope that it will offer additional
perspective and understanding on Rust.

* /The Rustonomicon/
I read through this guide to learn techniques for working with unsafe
Rust. I followed along with the implementation of Vec<T> at the end of
the book; an interesting exercise because the given code does not work
in modern Rust. I had to make my own changes as appropriate. My work
is in the =nomicon= directory.

* /LRtDW/
I followed along with the excellent articles of [[https://cliffle.com/p/dangerust][Learn Rust the
Dangerous Way]] to work with unsafe code and optimization in Rust. The
files in which I followed along with the series are in =dangerust=.
